"""Checkout input"""
input CheckoutInput {
  count: Int!
  id: ID!
}

"""The schema root for mutating data"""
type Mutation {
  """Checkout cart"""
  checkout(cart: [CheckoutInput!]!): [Product!]
}

"""A Product"""
type Product {
  description: String
  id: ID
  imageUrl: String
  name: String
  price: Int
  stockCount: Int
  summary: String
}

"""The schema root for fetching data."""
type Query {
  """To fetch product by id."""
  productById(id: ID!): Product

  """List of avaiable products."""
  products: [Product!]
}

"""The schema root for subscriptions"""
type Subscription {
  """Updates the available stock in real-time."""
  productUpdates: [Product!]
}