import { generate, type CodegenConfig } from '@graphql-codegen/cli'
import { Project } from 'ts-morph'

/**
 * Generates the .graphql schema file.
 */
export async function runCodegen(config: CodegenConfig) {
  await generate(config)

  console.log('GraphQL types generated successfully!')
  process.exit(0)
}

/**
 * @returns the generated codegen config
 */
export const getCodegenConfig = (
  targetFilePath: string,
  schema: NonNullable<CodegenConfig['schema']>
): CodegenConfig => {
  return {
    overwrite: true,
    schema,
    hooks: {
      afterAllFileWrite: [
        () => {
          /** Removing unused imports from the new generated file. To avoid tsc or eslint errors. */
          try {
            const project = new Project()
            project.addSourceFileAtPath(targetFilePath)

            const sourceFile = project.getSourceFile(targetFilePath)

            if (!sourceFile) {
              throw new Error(`File not found: ${targetFilePath}`)
            }
            sourceFile.organizeImports()
            project.saveSync()
          } catch (err) {
            console.error(
              'Error while organizing imports in types file generated by codegen.\n',
              err
            )
          }
        },
      ],
    },
    generates: {
      [`${targetFilePath}`]: {
        plugins: [
          'typescript',
          'typescript-operations',
          'typescript-react-apollo',
        ],
        config: {
          withHooks: true,
          withResultType: true,
          withMutationFn: true,
        },
      },
    },
  }
}
