import type { CodegenConfig } from '@graphql-codegen/cli'
import path from 'node:path'
import { Project } from 'ts-morph'
import sharedConfig from './shared/config'

/** The path where the generated types are emitted to. */
const targetFilePath = `${import.meta.dirname}/generated/typescript-react-apollo.tsx`

/**
 * Generates the types for the GraphQL client.
 * It parses the .graphql schema file and outputs the .ts file.
 */
const config: CodegenConfig = {
  overwrite: true,
  schema: path.join(import.meta.dirname, sharedConfig.graphqlSdlPath),
  hooks: {
    afterAllFileWrite: [
      () => {
        /** Removing unused imports from the new generated file. To avoid tsc or eslint errors. */
        try {
          const project = new Project()
          project.addSourceFileAtPath(targetFilePath)

          const sourceFile = project.getSourceFile(targetFilePath)

          if (!sourceFile) {
            throw new Error(`File not found: ${targetFilePath}`)
          }
          sourceFile.organizeImports()
          project.saveSync()
        } catch (err) {
          console.error(
            'Error while organizing imports in types file generated by codegen.\n',
            err
          )
        }
      },
    ],
  },
  generates: {
    [`${targetFilePath}`]: {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-apollo',
      ],
      config: {
        withHooks: true,
        withResultType: true,
        withMutationFn: true,
      },
    },
  },
}

export default config
